package restaurantapp.server.db;

import java.util.Arrays;
import java.util.List;

public class Constants {
    public static List<String> emails = Arrays.asList("lassannupola-1701@yopmail.com",
            "wigippawucu-0686@yopmail.com",
            "adudamme-4838@yopmail.com",
            "erroppuqass-3793@yopmail.com",
            "sijazisseh-4222@yopmail.com",
            "iffennannuppe-7732@yopmail.com",
            "marrommakani-9194@yopmail.com",
            "urripizeh-1523@yopmail.com",
            "etisazass-1796@yopmail.com",
            "fiffegaffe-8512@yopmail.com",
            "ajapaddu-7260@yopmail.com",
            "silijimu-9057@yopmail.com",
            "ogapoxaddu-0018@yopmail.com",
            "epalasu-0361@yopmail.com",
            "oddajajy-5136@yopmail.com",
            "unabesov-5536@yopmail.com",
            "kyzygedym-3269@yopmail.com",
            "kaddipeni-8242@yopmail.com",
            "funisesan-2050@yopmail.com",
            "girrihiddeq-6061@yopmail.com",
            "deqaxafyc-2988@yopmail.com",
            "zaffevollass-5094@yopmail.com",
            "affisselleq-4425@yopmail.com",
            "affezofo-9652@yopmail.com",
            "gattixozep-9520@yopmail.com",
            "xotossafy-7738@yopmail.com",
            "ittazorropp-2023@yopmail.com",
            "zannihuki-9260@yopmail.com",
            "fotezammonn-1323@yopmail.com",
            "niffissemu-0580@yopmail.com",
            "xodebimmu-2523@yopmail.com",
            "kakafessenn-0556@yopmail.com",
            "taffororu-4700@yopmail.com",
            "lobewemmux-7836@yopmail.com",
            "cugozele-2662@yopmail.com",
            "eqerihell-1262@yopmail.com",
            "esimmahytty-4802@yopmail.com",
            "xesikybenne-4090@yopmail.com",
            "ifogivaz-4508@yopmail.com",
            "yffarunna-9698@yopmail.com",
            "ciluhyffy-9815@yopmail.com"
    );

    public static List<String> names = Arrays.asList("Mnemosyne",
            "Lykourgos",
            "Anupam",
            "Prabhakar",
            "Parthenia",
            "Fionnuala",
            "Gaia",
            "Lochan",
            "Pegasus",
            "Osgar",
            "Wassa",
            "Iokaste",
            "Shrivatsa",
            "Ethelthryth",
            "Pooja",
            "Praxis",
            "Govannon",
            "Sigeweard",
            "Chloris",
            "Cynemar",
            "Esc",
            "Kamakshi",
            "Kore",
            "Nilima",
            "Sima",
            "Wigberht",
            "Ajit",
            "Vasu",
            "Terpsichore",
            "Aigle",
            "Shrivatsa",
            "Anika",
            "Hemera",
            "Raja",
            "Amrita",
            "Bedivere",
            "Conlaoch",
            "Jaywant",
            "Kaur",
            "Ranj",
            "Zephyr");


}